import type { Metadata } from "next"
import localFont from "next/font/local"

import "@/styles/global.css"
import { ThemeProvider } from "@/components/layout/theme-provider"
import { Toaster } from "@/components/_ui/sonner"

const livvic = localFont({
  src: [
    {
      path: "./fonts/Livvic-Thin.ttf",
      weight: "100",
      style: "normal"
    },
    {
      path: "./fonts/Livvic-ThinItalic.ttf",
      weight: "100",
      style: "italic"
    },
    {
      path: "./fonts/Livvic-ExtraLight.ttf",
      weight: "200",
      style: "normal"
    },
    {
      path: "./fonts/Livvic-ExtraLightItalic.ttf",
      weight: "200",
      style: "italic"
    },
    {
      path: "./fonts/Livvic-Light.ttf",
      weight: "300",
      style: "normal"
    },
    {
      path: "./fonts/Livvic-LightItalic.ttf",
      weight: "300",
      style: "italic"
    },
    {
      path: "./fonts/Livvic-Regular.ttf",
      weight: "400",
      style: "normal"
    },
    {
      path: "./fonts/Livvic-Italic.ttf",
      weight: "400",
      style: "italic"
    },
    {
      path: "./fonts/Livvic-Medium.ttf",
      weight: "500",
      style: "normal"
    },
    {
      path: "./fonts/Livvic-MediumItalic.ttf",
      weight: "500",
      style: "italic"
    },
    {
      path: "./fonts/Livvic-SemiBold.ttf",
      weight: "600",
      style: "normal"
    },
    {
      path: "./fonts/Livvic-SemiBoldItalic.ttf",
      weight: "600",
      style: "italic"
    },
    {
      path: "./fonts/Livvic-Bold.ttf",
      weight: "700",
      style: "normal"
    },
    {
      path: "./fonts/Livvic-BoldItalic.ttf",
      weight: "700",
      style: "italic"
    },
    {
      path: "./fonts/Livvic-Black.ttf",
      weight: "900",
      style: "normal"
    },
    {
      path: "./fonts/Livvic-BlackItalic.ttf",
      weight: "900",
      style: "italic"
    }
  ],
  variable: "--font-livvic",
  display: "swap"
})

export const metadata: Metadata = {
  title: "E-Games",
  description: "Generated by create next app"
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`dark ${livvic.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster duration={3000} position="top-right" />
        </ThemeProvider>
      </body>
    </html>
  )
}
