import type { Metadata } from "next"
import { Livvic } from "next/font/google"

import "@/styles/global.css"
import { ThemeProvider } from "@/components/layout/theme-provider"
import { Toaster } from "@/components/_ui/sonner"

export const metadata: Metadata = {
  title: "E-Games",
  description: "Generated by create next app"
}

const livvic = Livvic({
  subsets: ["latin"],
  weight: "400"
})

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${livvic.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster duration={3000} position="top-right" />
        </ThemeProvider>
      </body>
    </html>
  )
}
